# Generated by Django 3.2.4 on 2021-11-09 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 11, 10, 2, 12, 48, 391131))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 11, 10, 2, 12, 48, 391131))),
            ],
        ),
    ]
